<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE language [
    <!ELEMENT language ANY>
    <!ELEMENT text (source,output)>
    <!ELEMENT source ANY>
    <!ELEMENT output ANY>
    <!ATTLIST language
        src       CDATA    #REQUIRED
        output    CDATA    #REQUIRED
        name      CDATA    #REQUIRED
        native    CDATA    #REQUIRED
    >
]>
<language src="en" output="ja" name="Japanese" native="日本">
    <text>
        <source>That option is not set.</source>
        <output>このオプションが設定されていません。</output>
    </text>
    <text>
        <source>Error:</source>
        <output>エラー：</output>
    </text>
    <text>
        <source>Error: The proper database credentials were not passed.</source>
        <output>エラー：適切なデータベースの資格情報が渡されませんでした。</output>
    </text>
    <text>
        <source>Error: The database result resource is not currently set.</source>
        <output>エラー：データベース結果リソースは、現在設定されていません。</output>
    </text>
    <text>
        <source>Error: Could not connect to database. Connection Error #%1: %2.</source>
        <output>エラー：データベースに接続できませんでした。接続エラー＃%1： %2。</output>
    </text>
    <text>
        <source>Error: There was an error connecting to the database.</source>
        <output>エラー：データベースに接続エラーが発生しました。</output>
    </text>
    <text>
        <source>Error: The database file was not passed.</source>
        <output>エラー：データベースファイルが渡されませんでした。</output>
    </text>
    <text>
        <source>Error: The database file does not exists.</source>
        <output>エラー：データベースファイルが存在しません。</output>
    </text>
    <text>
        <source>Error: That doctype is not allowed.</source>
        <output>エラー：そのdoctypeは許可されていません。</output>
    </text>
    <text>
        <source>The child element passed is not an instance of Moc10_Dom_Child.</source>
        <output>渡された子要素はMoc10_Dom_Childのインスタンスではありません。</output>
    </text>
    <text>
        <source>One or more of the child elements passed is not an instance of Moc10_Dom_Child.</source>
        <output>渡された子要素の1つまたは複数のMoc10_Dom_Childのインスタンスではありません。</output>
    </text>
    <text>
        <source>That feed URL cannot be read at this time. Please try again later.</source>
        <output>そのフィードのURLは、この時点で読み取ることができません。後でもう一度やり直してください。</output>
    </text>
    <text>
        <source>Error: The feed item template is not set.</source>
        <output>エラー：フィード項目テンプレートが設定されていません。</output>
    </text>
    <text>
        <source>Error: The feed currently has no content.</source>
        <output>エラーは：フィードは、現在はコンテンツがありません。</output>
    </text>
    <text>
        <source>Error: The feed type must be only RSS or ATOM.</source>
        <output>エラー：フィードの種類は、RSSやATOMする必要があります。</output>
    </text>
    <text>
        <source>Error: The file is not an accepted file format.</source>
        <output>エラー：ファイルが受け入れられたファイル形式ではありません。</output>
    </text>
    <text>
        <source>Error: The file already exists.</source>
        <output>エラー：ファイルが既に存在しています。</output>
    </text>
    <text>
        <source>Error: The directory does not exist.</source>
        <output>エラー：ディレクトリが存在しません。</output>
    </text>
    <text>
        <source>Error: The upload directory does not exist.</source>
        <output>エラー：存在しないディレクトリをアップロードしてください。</output>
    </text>
    <text>
        <source>Error: The file uploaded is too big.</source>
        <output>エラーは：アップロードされたファイルが大きすぎます。</output>
    </text>
    <text>
        <source>Error: The image file uploaded is too big.</source>
        <output>エラーは：アップロードされた画像ファイルが大きすぎます。</output>
    </text>
    <text>
        <source>Error: There was an error in uploading the file.</source>
        <output>エラー：ファイルをアップロード中にエラーが発生しました。</output>
    </text>
    <text>
        <source>Error: There was an error in uploading the image file.</source>
        <output>エラー：画像のファイルをアップロード中にエラーが発生しました。</output>
    </text>
    <text>
        <source>Error: Permission denied.</source>
        <output>エラー：アクセスが拒否されました。</output>
    </text>
    <text>
        <source>Error: The parameter passed is not an array.</source>
        <output>エラーは：渡されたパラメータは配列ではありません。</output>
    </text>
    <text>
        <source>Error: The array passed must contain at least one type.</source>
        <output>エラー：少なくとも1つのタイプが含まれている必要が渡された配列。</output>
    </text>
    <text>
        <source>Error: The file or directory (%1) is not writable.</source>
        <output>エラーは：ファイルまたはディレクトリ（%1）が書き込み可能ではありません。</output>
    </text>
    <text>
        <source>Error: There are no form elements declared for this form object.</source>
        <output>エラーは：no形式の要素は、このフォームオブジェクトの宣言があります。</output>
    </text>
    <text>
        <source>Error: That input type is not allowed.</source>
        <output>エラーが発生しました：その入力タイプが許可されていません。</output>
    </text>
    <text>
        <source>Error: The required flag must be a boolean value.</source>
        <output>エラー：必要なフラグはブール値でなければなりません。</output>
    </text>
    <text>
        <source>Error: That type validator is not allowed.</source>
        <output>エラー：そのタイプのバリデータが許可されていません。</output>
    </text>
    <text>
        <source>Error: The condition must be a boolean.</source>
        <output>エラー：条件がブール値である必要があります。</output>
    </text>
    <text>
        <source>This field is required.</source>
        <output>このフィールドは必須です。</output>
    </text>
    <text>
        <source>This field value must %1 contain alphanumeric characters.</source>
        <output>このフィールドの値は%1文字の英数字を使用する必要があります。</output>
    </text>
    <text>
        <source>This field value must %1 contain characters of the alphabet.</source>
        <output>このフィールドの値は%1はアルファベットの文字が含まれている必要があります。</output>
    </text>
    <text>
        <source>This field value is %1 between %2 and %3.</source>
        <output>このフィールドの値の間に%1%2%3。</output>
    </text>
    <text>
        <source>This field value format is %1 a correct email format.</source>
        <output>このフィールドの値の形式は%1正しいメール形式です。</output>
    </text>
    <text>
        <source>This field value does not equal the correct value.</source>
        <output>このフィールドの値は正しい値と等しくありません。</output>
    </text>
    <text>
        <source>This field value is %1 greater than %2.</source>
        <output>このフィールドの値は%2以上%1より大きいです。</output>
    </text>
    <text>
        <source>This field value length is %1 equal to %2 characters long.</source>
        <output>このフィールドの値の長さは%1%2文字の長さ％に相当する。</output>
    </text>
    <text>
        <source>This field value length is %1 between %2 and %3.</source>
        <output>このフィールド値の長さの間に%1%2%3。</output>
    </text>
    <text>
        <source>This field value length must be %1 %2 characters long.</source>
        <output>このフィールドの値の長さは%1長%2文字以下でなければなりません。</output>
    </text>
    <text>
        <source>This field value is %1 less than %2.</source>
        <output>このフィールドの値は、%1%2未満である。</output>
    </text>
    <text>
        <source>This field value is %1 empty.</source>
        <output>このフィールドの値は%1は空です。</output>
    </text>
    <text>
        <source>This field value is %1 a number.</source>
        <output>このフィールドの値は%1の番号です。</output>
    </text>
    <text>
        <source>This field value format is %1 correct.</source>
        <output>このフィールドの値の形式は%1正しいことを確認します。</output>
    </text>
    <text>
        <source>The parameter passed must be an array.</source>
        <output>パラメータは配列でなければなりません渡されます。</output>
    </text>
    <text>
        <source>The array parameter passed must contain an array.</source>
        <output>配列パラメータは、配列が含まれている必要があります渡されます。</output>
    </text>
    <text>
        <source>not</source>
        <output>は</output>
    </text>
    <text>
        <source>only</source>
        <output>のみ</output>
    </text>
    <text>
        <source>under</source>
        <output>下</output>
    </text>
    <text>
        <source>at least</source>
        <output>少なくとも</output>
    </text>
    <text>
        <source>Sunday</source>
        <output>日曜日</output>
    </text>
    <text>
        <source>Monday</source>
        <output>月曜日</output>
    </text>
    <text>
        <source>Tuesday</source>
        <output>火曜日</output>
    </text>
    <text>
        <source>Wednesday</source>
        <output>水曜日</output>
    </text>
    <text>
        <source>Thursday</source>
        <output>木曜日</output>
    </text>
    <text>
        <source>Friday</source>
        <output>金曜日</output>
    </text>
    <text>
        <source>Saturday</source>
        <output>土曜日</output>
    </text>
    <text>
        <source>January</source>
        <output>1月</output>
    </text>
    <text>
        <source>February</source>
        <output>2月</output>
    </text>
    <text>
        <source>March</source>
        <output>3月</output>
    </text>
    <text>
        <source>April</source>
        <output>4月</output>
    </text>
    <text>
        <source>May</source>
        <output>5月</output>
    </text>
    <text>
        <source>June</source>
        <output>6月</output>
    </text>
    <text>
        <source>July</source>
        <output>7月</output>
    </text>
    <text>
        <source>August</source>
        <output>8月</output>
    </text>
    <text>
        <source>September</source>
        <output>9月</output>
    </text>
    <text>
        <source>October</source>
        <output>10月</output>
    </text>
    <text>
        <source>November</source>
        <output>11月</output>
    </text>
    <text>
        <source>December</source>
        <output>12月</output>
    </text>
    <text>
        <source>Error: There was an error connecting to the FTP server %1.</source>
        <output>エラーは：FTPサーバー%1に接続してエラーが発生しました。</output>
    </text>
    <text>
        <source>Error: There was an error connecting to the FTP server %1 with those credentials.</source>
        <output>エラー：これらの資格情報を使用してFTPサーバー%1に接続してエラーが発生しました。</output>
    </text>
    <text>
        <source>Error: There was an error changing to the directory %1.</source>
        <output>エラーは：ディレクトリ%1に変更する際にエラーが発生しました。</output>
    </text>
    <text>
        <source>Error: There was an error making the directory %1.</source>
        <output>エラーは：ディレクトリ%1を作成中にエラーが発生しました。</output>
    </text>
    <text>
        <source>Error: There was an error removing the directory %1.</source>
        <output>エラーは：ディレクトリ%1を削除中にエラーが発生しました。</output>
    </text>
    <text>
        <source>Error: There was an error getting the file %1.</source>
        <output>エラーは：ファイル%1を取得中にエラーが発生しました。</output>
    </text>
    <text>
        <source>Error: There was an error putting the file %1.</source>
        <output>エラーは：ファイル%1を入れてエラーが発生しました。</output>
    </text>
    <text>
        <source>Error: There was an error renaming the file %1.</source>
        <output>エラー：ファイルの%1の名前を変更中にエラーが発生しました。</output>
    </text>
    <text>
        <source>Error: There was an error changing the permission of %1.</source>
        <output>エラーが発生：%1のアクセス許可を変更中にエラーが発生しました。</output>
    </text>
    <text>
        <source>Error: There was an error removing the file %1.</source>
        <output>エラーは：ファイル%1を削除中にエラーが発生しました。</output>
    </text>
    <text>
        <source>Error: You must define a width and height for a new image object.</source>
        <output>エラー：あなたは幅と高さを新しい画像オブジェクトを定義する必要があります。</output>
    </text>
    <text>
        <source>Error: That image type is not supported. Only GIF, JPG and PNG image types are supported.</source>
        <output>エラー：そのイメージの種類はサポートされていません。のみのGIF、JPGおよびPNGイメージのタイプがサポートされています。</output>
    </text>
    <text>
        <source>Error: This image file is already a %1 image file.</source>
        <output>エラー：これはイメージファイルが既に%1イメージファイルです。</output>
    </text>
    <text>
        <source>Error: The language file %1 does not exist.</source>
        <output>エラーは：言語ファイル%1は存在しません。</output>
    </text>
    <text>
        <source>Error: Your output language selection is not valid.</source>
        <output>エラー：あなたの出力言語の選択が有効ではありません。</output>
    </text>
    <text>
        <source>Error: Your source language selection is not valid.</source>
        <output>エラー：あなたのソース言語の選択が有効ではありません。</output>
    </text>
    <text>
        <source>Error: Both the output and source language selections are the same. Please choose again.</source>
        <output>エラーは：両方の出力、ソース言語の選択は同じです。もう一度選択してください。</output>
    </text>
    <text>
        <source>Error: There was an error processing that Google Translate URL. Please check your API key.</source>
        <output>エラー：エラーが処理がされたGoogle翻訳のURLを確認します。あなたのAPIキーを確認してください。</output>
    </text>
    <text>
        <source>Error: There was an error processing that XML file.</source>
        <output>エラーは：そのXMLファイルのエラー処理があった。</output>
    </text>
    <text>
        <source>Error: At least one of the array keys must be 'email'.</source>
        <output>エラーは：少なくとも配列のキーの1つで'メールアドレス'する必要があります。</output>
    </text>
    <text>
        <source>Error: The parameter passed must either be a valid file or an instance of Moc10_File.</source>
        <output>エラー：パラメータは、有効なファイルまたはMoc10_Fileのインスタンスである必要があります渡されます。</output>
    </text>
    <text>
        <source>Error: The message body elements are not set.</source>
        <output>エラー：メッセージ本文の要素が設定されていません。</output>
    </text>
    <text>
        <source>Error: That page does not exist.</source>
        <output>エラーは：このページには存在しません。</output>
    </text>
    <text>
        <source>Error: The PDF does not have enough pages in which to order.</source>
        <output>エラー：PDFは、注文するのに十分なページを持っていません。</output>
    </text>
    <text>
        <source>Error: The pages array passed does not contain the same number of pages as the PDF.</source>
        <output>エラー：PDFとして同じページ番号が含まれていません渡されたページの配列を返します。</output>
    </text>
    <text>
        <source>Error: The pages array passed contains a page that does not exist.</source>
        <output>エラーは：渡されたページの配列が存在しないページが含まれています。</output>
    </text>
    <text>
        <source>Error: The rotation parameter must be between -90 and 90 degrees.</source>
        <output>エラー：回転パラメータは、-90度から90度の間である必要があります。</output>
    </text>
    <text>
        <source>Error: The render parameter must be an integer between 0 and 7.</source>
        <output>エラーは：レンダリングパラメータは0から7までの整数でなければなりません。</output>
    </text>
    <text>
        <source>Error: That font is not contained within the standard PDF fonts.</source>
        <output>エラー：そのフォントは、標準のPDFフォント内に含まれていない。</output>
    </text>
    <text>
        <source>Error: That font has not been added to the PDF.</source>
        <output>エラー：そのフォントをPDFに追加されていません。</output>
    </text>
    <text>
        <source>Error: That page has not been defined.</source>
        <output>エラー：このページには、定義されていません。</output>
    </text>
    <text>
        <source>Error: PNG alpha channels are not supported. Only 8-bit transparent PNG images are supported.</source>
        <output>エラー：PNGのアルファチャネルはサポートされていません。 8ビットのみ透過PNG画像がサポートされています。</output>
    </text>
    <text>
        <source>Error: The file already exists and it cannot be overwritten. Please specify a new filename.</source>
        <output>エラー：ファイルが既に存在し、それが上書きすることはできません。新しいファイル名を指定してください。</output>
    </text>
    <text>
        <source>Error: The argument passed must be an array.</source>
        <output>エラー：配列でなければなりません渡される引数。</output>
    </text>
    <text>
        <source>Error: A width and height must be passed.</source>
        <output>エラー：幅と高さが渡される必要があります。</output>
    </text>
    <text>
        <source>Error: A page index must be passed.</source>
        <output>エラー：ページのインデックスが渡される必要があります。</output>
    </text>
    <text>
        <source>The field '%1' does not exist.</source>
        <output>フィールド'%1'は存在しません。</output>
    </text>
    <text>
        <source>The parameter passed must be either an array or null.</source>
        <output>渡されたパラメータは配列またはnullにする必要があります。</output>
    </text>
    <text>
        <source>This primary ID of this table either is not set or does not exist.</source>
        <output>このテーブルのこのプライマリIDのいずれか、または設定されていない存在しません。</output>
    </text>
    <text>
        <source>The field and value parameters were not defined to describe the row(s) to delete.</source>
        <output>フィールドと値のパラメータは、行（s）を削除する方法について説明して定義されていない。</output>
    </text>
    <text>
        <source>The mobile site is not set.</source>
        <output>モバイルサイトが設定されていません。</output>
    </text>
    <text>
        <source>The standard site is not set.</source>
        <output>標準的なサイトが設定されていません。</output>
    </text>
</language>